// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzMdhyiDYYMWKniUN-i8Y_bBVRTqJqKJ8',
    appId: '1:1095914767766:web:cc87cc1e8e99db4deb89b7',
    messagingSenderId: '1095914767766',
    projectId: 'maumasak-ta',
    authDomain: 'maumasak-ta.firebaseapp.com',
    storageBucket: 'maumasak-ta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtd5j4wyFVeN4JTpj9Hy6jxZ7nCQVyiZw',
    appId: '1:1095914767766:android:37018b837e39b62beb89b7',
    messagingSenderId: '1095914767766',
    projectId: 'maumasak-ta',
    storageBucket: 'maumasak-ta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabJR6aEdCat2k5A0FZjY0730S-2e9fjc',
    appId: '1:1095914767766:ios:79ac85dbc674ee59eb89b7',
    messagingSenderId: '1095914767766',
    projectId: 'maumasak-ta',
    storageBucket: 'maumasak-ta.appspot.com',
    iosClientId: '1095914767766-ef9cl002d3g4ussr4fuoeof24j7m2amv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mauMasak',
  );
}
